version: "2.1"
services:
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=TIMEZONETOCHANGE
    volumes:
      - ./heimdall:/config
      - ./heimdall/www/img:/var/www/localhost/heimdall/public/img
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
